server: 
  port: 3344 
  
spring:
  application:
    name:  swt-chthr-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lxc1234pm/swt-chthr-config.git #GitHub上面的git仓库名字
 

